package: d2u_linkbox
version: '1.2.5'
author: Tobias Krais

page:
    title: 'translate:d2u_linkbox'
    perm: 'd2u_linkbox[]'
    icon: rex-icon fa-window-maximize
    subpages:
        linkbox: { title: 'translate:d2u_linkbox_linkbox', icon: rex-icon fa-window-maximize }
        category: { title: 'translate:d2u_helper_categories', icon: rex-icon rex-icon-open-category, perm: 'd2u_linkbox[edit_data]' }
        settings: { title: 'translate:d2u_helper_settings', icon: rex-icon rex-icon-system, itemclass: pull-right, perm: 'd2u_linkbox[settings]' }
        setup: { title: 'translate:d2u_helper_setup', icon: rex-icon rex-icon-install, itemclass: pull-right, perm: 'd2u_linkbox[settings]' }

requires:
    packages:
        d2u_helper: '>=1.5.5'