package: d2u_linkbox
version: '1.1'
author: Tobias Krais

page:
    title: 'translate:d2u_linkbox'
    perm: d2u_linkbox[]
    icon: rex-icon fa-window-maximize
    subpages:
        linkbox: { title: 'translate:d2u_linkbox_linkbox', icon: rex-icon fa-window-maximize }
        category: { title: 'translate:d2u_linkbox_categories', icon: rex-icon rex-icon-open-category, perm: d2u_linkbox[edit_data] }
        setup: { title: 'translate:d2u_helper_setup', icon: rex-icon rex-icon-install, perm: d2u_linkbox[settings] }

requires:
    redaxo: '>=5.3.0'
    php:
        version: '>=5.6'
    packages:
        d2u_helper: '>=1.3.0'