package: d2u_linkbox
version: '1.6.2'
author: Tobias Krais

page:
    title: 'translate:d2u_linkbox'
    perm: 'd2u_linkbox[]'
    icon: rex-icon fa-window-maximize
    subpages:
        linkbox: { title: 'translate:d2u_linkbox_linkbox', icon: rex-icon fa-window-maximize }
        category: { title: 'translate:d2u_helper_categories', icon: rex-icon rex-icon-open-category, perm: 'd2u_linkbox[edit_data]' }
        settings:
            icon: rex-icon rex-icon-system
            title: ''
            itemClass: pull-right
            subpages:
                settings: { title: 'translate:d2u_helper_settings', icon: rex-icon rex-icon-system, perm: 'd2u_linkbox[settings]' }
                setup: { title: 'translate:d2u_helper_setup', icon: rex-icon rex-icon-install, perm: 'd2u_linkbox[settings]' }
        help:
            title: ''
            icon: rex-icon rex-icon-help
            itemClass: pull-right
            subpages:
                changelog: { title: 'translate:d2u_helper_help_chapter_changelog' }

requires:
    packages:
        d2u_helper: '>=2.2.1'
    php: '>=8.0'

conflicts:
    packages:
        d2u_courses: '<3.6.0'
        d2u_immo: '<1.4.0'
        d2u_machinery: '<1.6.0'

default_config:
    default_sort: 'name'

installer_ignore:
    - .github