package: d2u_linkbox
version: '1.5.1'
author: Tobias Krais

page:
    title: 'translate:d2u_linkbox'
    perm: 'd2u_linkbox[]'
    icon: rex-icon fa-window-maximize
    subpages:
        linkbox: { title: 'translate:d2u_linkbox_linkbox', icon: rex-icon fa-window-maximize }
        category: { title: 'translate:d2u_helper_categories', icon: rex-icon rex-icon-open-category, perm: 'd2u_linkbox[edit_data]' }
        setup: { title: 'translate:d2u_helper_setup', icon: rex-icon rex-icon-install, itemClass: pull-right, perm: 'd2u_linkbox[settings]' }
        settings: { title: 'translate:d2u_helper_settings', icon: rex-icon rex-icon-system, itemClass: pull-right, perm: 'd2u_linkbox[settings]' }

requires:
    packages:
        d2u_helper: '>=1.14.0'
    php: '>=8.0'

default_config:
    default_sort: 'name'

installer_ignore:
    - .github